name: Spruce and Hemlock Country Store
favicon: null
layout_spectrum: 0.58226
typography_spectrum: 0.60091
title: Retail Store
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#353535'
    - '#949494'
    - '#d2d2d2'
    - '#060000'
  brandStrength: 0.9619526371825486
  lightness: 0.6452016502153128
  saturation: 0.7771636496763676
  rhythmicContrast: 0.25
purpose: []
