name: Spruce and Hemlock Country Store
favicon: null
layout_spectrum: 0
typography_spectrum: 0.11436948389746249
title: Retail Store
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d3b32'
    - '#f6f6eb'
    - '#d0d3cc'
    - '#6a584b'
    - '#a4a49c'
  brandStrength: 0.9619526371825486
  lightness: 0.6452016502153128
  saturation: 0.7771636496763676
  rhythmicContrast: 0.23634940152987838
purpose: []
