name: Spruce and Hemlock Country Store
favicon: null
layout_spectrum: 0.6354223852977157
typography_spectrum: 0.11436948389746249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffbe2'
    - '#c8ac86'
    - '#282018'
    - '#735329'
  brandStrength: 0.9619526371825486
  lightness: 0.6452016502153128
  saturation: 0.7771636496763676
  rhythmicContrast: 0.23634940152987838
purpose: []
